import type { AnalyzeResult, Limits, Provenance } from "../../src/api/types";

// 1x1 white JPEG, base64.
export const JPEG_B64 =
  "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/yQALCAABAAEBAREA/8wABgAQEAX/2gAIAQEAAD8A0s8g/9k=";

export const limits = (over: Partial<Limits> = {}): Limits => ({
  max_image_size_mb: 20, max_video_size_mb: 200, max_video_duration_seconds: 120,
  image_extensions: [".jpg", ".jpeg", ".png", ".webp"], video_extensions: [".mp4", ".mov", ".mkv", ".avi"],
  auth_required: false, explanations_available: true, content_credentials_available: true,
  image_analysis_experimental: true, upload_timeout_seconds: 120, request_timeout_seconds: 120, ...over,
});

export const provenance = (status: Provenance["status"], withSummary = false): Provenance => ({
  status, reason: "x", elapsed_ms: 2, notice: "separate signal",
  summary: withSummary ? {
    signer: { common_name: "Harbourline Photo Desk", organization: "Harbourline Test CA", algorithm: "Es256" },
    signed_at: null, timestamp: "absent", claim_generator: [{ name: "field-cam", version: "4.2" }], title: "harbour.jpg",
    actions: [{ action: "c2pa.created", digital_source_type: { code: "trainedAlgorithmicMedia", label: "Generated by AI", ai_generated: true } }],
    declares_ai_generated: true, ingredients: [], manifest_count: 1,
    validation_codes: { success: [], informational: [], failure: status === "INVALID" ? ["assertion.dataHash.mismatch"] : [] },
  } : null,
});

export const video = (over: Partial<AnalyzeResult> = {}): AnalyzeResult => ({
  request_id: "6f1c2a9e4b7d4e0f9a3c1b2d5e6f7a8b", media_type: "video", verdict: "likely_manipulated",
  base_verdict: "likely_manipulated", p_fake: 0.9731, confidence: 0.9731, gated: false, quality_reasons: [],
  uncertainty_reasons: [], warnings: [], frames_used: 4, stopping_reason: "confident_singleton_k4", frame_count: 398,
  faces_detected: null, stages: [{ stage: 4, p_fake: 0.9731, set: ["fake"], verdict: "likely_manipulated" }],
  timeline: [0, 95, 189, 284].map((fi, i) => ({ slot: i * 4, frame_index: fi, timestamp_s: fi / 30, logit: 3.1, p_fake_frame: 0.95 - i * 0.02,
    added_at_stage: 4, quality_flags: i === 2 ? ["LOW_SHARPNESS"] : [] })),
  model: { name: "student_distilled_p80", version: "student_distilled_p80+onnx-fp32:4e365f0d9942" }, device: "cpu",
  timings_ms: { upload_ms: 31, validation_ms: 44, queue_ms: 0.2, extraction_ms: 702.4, inference_ms: 12.7, gate_ms: 5.1,
    provenance_ms: 3.1, total_ms: 811.9 },
  experimental: false, experimental_reason: null, explanation: null, provenance: provenance("ABSENT"),
  notice: "Automated estimate from a model evaluated on FaceForensics++ development data only.", ...over,
});

export const image = (over: Partial<AnalyzeResult> = {}): AnalyzeResult => video({
  media_type: "image", verdict: "likely_real", base_verdict: "likely_real", p_fake: 0.026, confidence: 0.974, frames_used: 1,
  stopping_reason: null, frame_count: null, faces_detected: 1, stages: [],
  timeline: [{ frame_index: 0, logit: -3.6, p_fake_frame: 0.026, quality_flags: [] }], experimental: true,
  experimental_reason: "Still-image analysis is experimental: the calibration and quality thresholds were fitted on video frames, not photographs.",
  ...over,
});

/** Controllable stand-in for XMLHttpRequest. */
export class MockXHR {
  static last: MockXHR | null = null;
  method = ""; url = ""; headers: Record<string, string> = {}; body: unknown = null;
  status = 0; responseText = ""; responseType = ""; timeout = 0; aborted = false;
  upload: { onprogress: ((e: ProgressEvent) => void) | null; onload: (() => void) | null } = { onprogress: null, onload: null };
  onload: (() => void) | null = null; onerror: (() => void) | null = null;
  ontimeout: (() => void) | null = null; onabort: (() => void) | null = null;
  constructor() { MockXHR.last = this; }
  open(m: string, u: string) { this.method = m; this.url = u; }
  setRequestHeader(k: string, v: string) { this.headers[k] = v; }
  send(b: unknown) { this.body = b; }
  abort() { this.aborted = true; this.onabort?.(); }
  progress(loaded: number, total: number) { this.upload.onprogress?.({ lengthComputable: true, loaded, total } as ProgressEvent); }
  respond(status: number, body: unknown) {
    this.upload.onload?.();
    this.status = status;
    this.responseText = typeof body === "string" ? body : JSON.stringify(body);
    this.onload?.();
  }
}
