"""Safe, bounded summary of a C2PA manifest store for API/UI display.

Raw manifests are attacker-controlled. Only an allow-listed subset is kept.
Strings are stripped of control/bidi characters and truncated. Values that
look like URLs or that hold binary/resource references are dropped, so no
manifest URL can reach a client that might follow it. Free-form assertion
data, thumbnails and certificates are never returned.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Any

MAX_STR = 120
MAX_ITEMS = 20
_URLISH = re.compile(r"^[a-z][a-z0-9+.-]*:|^//|^www\.", re.I)
KNOWN_ACTIONS = {
    "c2pa.created", "c2pa.opened", "c2pa.placed", "c2pa.edited", "c2pa.edited.metadata", "c2pa.color_adjustments",
    "c2pa.cropped", "c2pa.drawing", "c2pa.filtered", "c2pa.orientation", "c2pa.resized", "c2pa.converted",
    "c2pa.transcoded", "c2pa.repackaged", "c2pa.removed", "c2pa.published", "c2pa.redacted", "c2pa.watermarked",
    "c2pa.unknown", "c2pa.deleted", "c2pa.copied", "c2pa.produced", "c2pa.translated", "c2pa.dubbed",
    "c2pa.versioned", "c2pa.managed", "c2pa.enhanced", "c2pa.font.edited",
}
IPTC = "http://cv.iptc.org/newscodes/digitalsourcetype/"
SOURCE_TYPES = {
    "digitalCapture": "Captured with a digital device",
    "negativeFilm": "Scanned from negative film", "positiveFilm": "Scanned from positive film", "print": "Scanned print",
    "humanEdits": "Edited by a person", "compositeCapture": "Composite of captures",
    "algorithmicallyEnhanced": "Algorithmically enhanced", "dataDrivenMedia": "Data-driven media",
    "digitalArt": "Digital art", "virtualRecording": "Virtual recording", "compositeSynthetic": "Composite including synthetic elements",
    "trainedAlgorithmicMedia": "Generated by AI (trained algorithmic media)",
    "compositeWithTrainedAlgorithmicMedia": "Composite that includes AI-generated elements",
    "algorithmicMedia": "Generated algorithmically", "screenCapture": "Screen capture", "minorHumanEdits": "Minor human edits",
}
AI_TYPES = {"trainedAlgorithmicMedia", "compositeWithTrainedAlgorithmicMedia", "algorithmicMedia"}


def safe_text(value: Any, limit: int = MAX_STR) -> str | None:
    if not isinstance(value, str):
        return None
    cleaned = "".join(ch for ch in value if unicodedata.category(ch)[0] != "C")  # controls, format (bidi), unassigned
    cleaned = " ".join(cleaned.split())
    if not cleaned or _URLISH.search(cleaned):
        return None
    return cleaned[:limit] + ("…" if len(cleaned) > limit else "")


def _source_type(v: Any) -> dict[str, Any] | None:
    if not isinstance(v, str) or not v.startswith(IPTC):
        return None
    term = v[len(IPTC):]
    if term not in SOURCE_TYPES:
        return {"code": "other", "label": "Other source type", "ai_generated": False}
    return {"code": term, "label": SOURCE_TYPES[term], "ai_generated": term in AI_TYPES}


def _agent(a: Any) -> str | None:
    if isinstance(a, dict):
        return safe_text(a.get("name"), 60)
    return safe_text(a, 60)


def _actions(manifest: dict) -> list[dict[str, Any]]:
    out = []
    for assertion in manifest.get("assertions") or []:
        if not isinstance(assertion, dict) or not str(assertion.get("label", "")).startswith("c2pa.actions"):
            continue
        for act in (assertion.get("data") or {}).get("actions") or []:
            if not isinstance(act, dict) or len(out) >= MAX_ITEMS:
                continue
            code = act.get("action")
            out.append({"action": code if code in KNOWN_ACTIONS else "other",
                        "when": safe_text(act.get("when"), 40),
                        "software_agent": _agent(act.get("softwareAgent")),
                        "digital_source_type": _source_type(act.get("digitalSourceType"))})
    return out


def _codes(results: Any) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {"success": [], "informational": [], "failure": []}
    active = (results or {}).get("activeManifest") or {}
    for kind in out:
        for item in active.get(kind) or []:
            code = item.get("code") if isinstance(item, dict) else None
            if isinstance(code, str) and re.fullmatch(r"[A-Za-z0-9_.]{1,64}", code) and code not in out[kind]:
                out[kind].append(code)
    return {k: v[:MAX_ITEMS] for k, v in out.items()}


def summarize(store: dict[str, Any]) -> dict[str, Any]:
    manifests = store.get("manifests") or {}
    active = manifests.get(store.get("active_manifest")) or {}
    sig = active.get("signature_info") or {}
    gen = [g for g in active.get("claim_generator_info") or [] if isinstance(g, dict)][:3]
    ingredients = []
    for ing in (active.get("ingredients") or [])[:MAX_ITEMS]:
        if not isinstance(ing, dict):
            continue
        rel = ing.get("relationship")
        ingredients.append({"title": safe_text(ing.get("title"), 80),
                            "format": safe_text(ing.get("format"), 40),
                            "relationship": rel if rel in ("parentOf", "componentOf", "inputTo") else "other",
                            "has_own_credentials": bool(ing.get("active_manifest") or ing.get("manifest_data"))})
    actions = _actions(active)
    codes = _codes(store.get("validation_results"))
    return {
        "signer": {"common_name": safe_text(sig.get("common_name")), "organization": safe_text(sig.get("issuer")),
                   "algorithm": safe_text(sig.get("alg"), 16)},
        "signed_at": safe_text(sig.get("time"), 40),
        "timestamp": ("trusted" if "timeStamp.trusted" in codes["success"] else
                      "untrusted" if any(c.startswith("timeStamp") for c in codes["failure"] + codes["informational"])
                      else "present" if sig.get("time") else "absent"),
        "claim_generator": [{"name": safe_text(g.get("name"), 60), "version": safe_text(g.get("version"), 30)} for g in gen],
        "title": safe_text(active.get("title"), 80),
        "actions": actions,
        "declares_ai_generated": any((a["digital_source_type"] or {}).get("ai_generated") for a in actions),
        "ingredients": ingredients,
        "manifest_count": len(manifests),
        "validation_codes": codes,
    }
