"""Fixtures for configuard.training tests: synthetic manifests with an
OBVIOUS learnable signal (blue- vs. red-tinted checkerboards, generated by
configuard.training.synthetic) - purely for engineering pipeline
verification (task 20/21), never a deepfake-accuracy claim - see
docs/MODEL_CARD.md.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from configuard.datasets.manifest import write_manifest
from configuard.datasets.schema import Sample, SampleLabel, SampleMediaType
from configuard.media.cache import FaceCropCache
from configuard.media.face_detector import MockFaceDetector
from configuard.media.types import PreprocessingConfig as FacePreprocessingConfig
from configuard.training import synthetic

FFMPEG_AVAILABLE = shutil.which("ffmpeg") is not None


@pytest.fixture
def media_root(tmp_path: Path) -> Path:
    root = tmp_path / "media"
    root.mkdir()
    return root


def build_synthetic_image_manifest(media_root: Path, num_real: int = 4, num_fake: int = 4) -> list[Sample]:
    """ENGINEERING TEST DATA ONLY - see configuard.training.synthetic."""
    return synthetic.build_synthetic_image_samples(media_root, num_real, num_fake)


@pytest.fixture
def synthetic_image_manifest(media_root: Path) -> list[Sample]:
    return build_synthetic_image_manifest(media_root)


@pytest.fixture
def synthetic_manifest_path(tmp_path: Path, synthetic_image_manifest: list[Sample]) -> Path:
    path = tmp_path / "manifest.jsonl"
    write_manifest(synthetic_image_manifest, path)
    return path


@pytest.fixture
def full_frame_detector() -> MockFaceDetector:
    """Reports the WHOLE 64x64 synthetic image as a 'face' so alignment/
    cropping preserves the discriminative synthetic pattern."""
    return synthetic.full_frame_detector()


@pytest.fixture
def face_config() -> FacePreprocessingConfig:
    return FacePreprocessingConfig(
        detector_name="mock", detector_version="test", margin_ratio=0.0,
        output_size=(224, 224), min_face_size_px=1,
    )


@pytest.fixture
def face_cache(tmp_path: Path) -> FaceCropCache:
    return FaceCropCache(tmp_path / "face_cache")


@pytest.fixture
def synthetic_video_manifest(media_root: Path) -> list[Sample]:
    """One real + one fake tiny synthetic clip (ffmpeg lavfi), for the
    video-frame dataset path."""
    if not FFMPEG_AVAILABLE:
        pytest.skip("ffmpeg not available on PATH")
    samples = []
    specs = [("real_0.mp4", SampleLabel.REAL, "testsrc"), ("fake_0.mp4", SampleLabel.FAKE, "testsrc2")]
    for filename, label, pattern in specs:
        path = media_root / filename
        subprocess.run(
            [
                "ffmpeg", "-y", "-f", "lavfi",
                "-i", f"{pattern}=duration=2:size=64x64:rate=10",
                "-pix_fmt", "yuv420p", str(path),
            ],
            capture_output=True, check=True, timeout=30,
        )
        samples.append(
            Sample(
                sample_id=f"synthetic:{filename}", dataset_name="synthetic", dataset_version="v1",
                media_type=SampleMediaType.VIDEO, media_path=filename, label=label,
                source_id=filename, identity_id=filename,
            )
        )
    return samples
